"""align model constraints and todo enums

Revision ID: b93475648a93
Revises: 0001_initial
Create Date: 2026-08-01 04:52:17.257622
"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = 'b93475648a93'
down_revision: str | None = '0001_initial'
branch_labels: Sequence[str] | None = None
depends_on: Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq_refresh_tokens_token_hash'), 'refresh_tokens', type_='unique')
    op.drop_index(op.f('ix_refresh_tokens_token_hash'), table_name='refresh_tokens')
    op.create_index(op.f('ix_refresh_tokens_token_hash'), 'refresh_tokens', ['token_hash'], unique=True)
    op.drop_constraint(op.f('uq_roles_name'), 'roles', type_='unique')
    op.drop_index(op.f('ix_roles_name'), table_name='roles')
    op.create_index(op.f('ix_roles_name'), 'roles', ['name'], unique=True)
    op.alter_column('todos', 'status',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.Enum('pending', 'in_progress', 'completed', 'archived', name='todostatus', native_enum=False),
               existing_nullable=False)
    op.alter_column('todos', 'priority',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.Enum('low', 'medium', 'high', 'urgent', name='priority', native_enum=False),
               existing_nullable=False)
    op.drop_constraint(op.f('uq_users_email'), 'users', type_='unique')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=False)
    op.create_unique_constraint(op.f('uq_users_email'), 'users', ['email'], postgresql_nulls_not_distinct=False)
    op.alter_column('todos', 'priority',
               existing_type=sa.Enum('low', 'medium', 'high', 'urgent', name='priority', native_enum=False),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False)
    op.alter_column('todos', 'status',
               existing_type=sa.Enum('pending', 'in_progress', 'completed', 'archived', name='todostatus', native_enum=False),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False)
    op.drop_index(op.f('ix_roles_name'), table_name='roles')
    op.create_index(op.f('ix_roles_name'), 'roles', ['name'], unique=False)
    op.create_unique_constraint(op.f('uq_roles_name'), 'roles', ['name'], postgresql_nulls_not_distinct=False)
    op.drop_index(op.f('ix_refresh_tokens_token_hash'), table_name='refresh_tokens')
    op.create_index(op.f('ix_refresh_tokens_token_hash'), 'refresh_tokens', ['token_hash'], unique=False)
    op.create_unique_constraint(op.f('uq_refresh_tokens_token_hash'), 'refresh_tokens', ['token_hash'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
