import { NavLink, Outlet, useNavigate } from 'react-router-dom'
import { Bell, Bot, CheckSquare, LogOut, Menu, Shield, UserCircle, X } from 'lucide-react'
import { useState } from 'react'
import { useAuth } from '../hooks/useAuth'
import { useNotifications } from '../hooks/useApi'
import { useNotificationSocket } from '../hooks/useNotificationSocket'
import { Button } from '../components/ui'

export function AppLayout() {
  const { user, logout } = useAuth(); const navigate = useNavigate(); const [open, setOpen] = useState(false); const { data } = useNotifications(); useNotificationSocket()
  const links = [{ to: '/app', label: 'Tổng quan', icon: CheckSquare }, { to: '/app/ai', label: 'Trợ lý AI', icon: Bot }, { to: '/app/profile', label: 'Hồ sơ', icon: UserCircle }, ...(user?.roles.includes('admin') ? [{ to: '/app/admin', label: 'Quản trị', icon: Shield }] : [])]
  return <div className="min-h-screen bg-slate-50 text-slate-900"><header className="sticky top-0 z-20 border-b border-slate-200 bg-white/90 backdrop-blur"><div className="mx-auto flex h-16 max-w-7xl items-center justify-between px-4"><button className="flex items-center gap-2 font-bold text-indigo-700" onClick={() => navigate('/app')}><span className="grid size-9 place-items-center rounded-xl bg-indigo-600 text-white">✓</span> Todo AI</button><div className="flex items-center gap-2"><button className="relative rounded-xl p-2 hover:bg-slate-100" aria-label="Thông báo" onClick={() => navigate('/app/notifications')}><Bell size={20}/>{(data?.unread_count ?? 0) > 0 && <span className="absolute right-1 top-1 size-2 rounded-full bg-rose-500"/>}</button><button className="rounded-xl p-2 hover:bg-slate-100 md:hidden" aria-label="Mở menu" onClick={() => setOpen(!open)}>{open ? <X/> : <Menu/>}</button></div></div></header><div className="mx-auto flex max-w-7xl"><aside className={`${open ? 'block' : 'hidden'} fixed inset-x-0 top-16 z-10 border-b bg-white p-4 md:static md:block md:w-60 md:border-0 md:bg-transparent md:p-5`}><nav className="space-y-1">{links.map(({ to, label, icon: Icon }) => <NavLink key={to} to={to} end={to === '/app'} onClick={() => setOpen(false)} className={({ isActive }) => `flex items-center gap-3 rounded-xl px-3 py-2.5 text-sm font-medium ${isActive ? 'bg-indigo-50 text-indigo-700' : 'text-slate-600 hover:bg-white'}`}><Icon size={18}/>{label}</NavLink>)}<NavLink to="/app/notifications" className="flex items-center gap-3 rounded-xl px-3 py-2.5 text-sm font-medium text-slate-600 hover:bg-white"><Bell size={18}/>Thông báo</NavLink></nav><div className="mt-8 border-t border-slate-200 pt-4"><div className="mb-3 px-3 text-sm font-semibold">{user?.full_name || user?.email}</div><Button variant="ghost" className="w-full justify-start gap-3" onClick={() => void logout()}><LogOut size={18}/>Đăng xuất</Button></div></aside><main className="min-w-0 flex-1 p-4 md:p-8"><Outlet /></main></div></div>
}
