import { useEffect, useState } from 'react'
import { Bot, Send, Sparkles, Trash2 } from 'lucide-react'
import { aiApi } from '../api/ai'
import { getErrorMessage } from '../api/client'
import { Card, Button, Input } from '../components/ui'
import type { ChatMessage, Conversation } from '../types'

const prompts = ['Hướng dẫn tôi sử dụng ứng dụng', 'Giúp tôi ưu tiên công việc hôm nay', 'Cách chia nhỏ một công việc lớn?']

export function AiPage() {
  const [messages, setMessages] = useState<ChatMessage[]>([]); const [conversations, setConversations] = useState<Conversation[]>([])
  const [conversationId, setConversationId] = useState<string>(); const [input, setInput] = useState(''); const [sending, setSending] = useState(false); const [error, setError] = useState('')
  const refreshConversations = async () => { try { setConversations(await aiApi.conversations()) } catch { /* chat remains usable */ } }
  useEffect(() => { void refreshConversations() }, [])
  const openConversation = async (id: string) => { setError(''); try { const result = await aiApi.conversation(id); setConversationId(id); setMessages(result.messages) } catch (reason) { setError(getErrorMessage(reason, 'Không thể tải cuộc trò chuyện.')) } }
  const removeConversation = async (id: string) => { if (!confirm('Xóa cuộc trò chuyện này?')) return; setError(''); try { await aiApi.removeConversation(id); if (conversationId === id) { setConversationId(undefined); setMessages([]) }; await refreshConversations() } catch (reason) { setError(getErrorMessage(reason, 'Không thể xóa cuộc trò chuyện.')) } }
  const send = async (preset?: string) => { const text = (preset ?? input).trim(); if (!text || sending) return; setInput(''); setSending(true); setError(''); const local: ChatMessage = { id: crypto.randomUUID(), role: 'user', content: text, created_at: new Date().toISOString() }; setMessages(items => [...items, local]); try { const response = await aiApi.chat(text, conversationId); setConversationId(response.conversation_id); setMessages(items => [...items, { id: crypto.randomUUID(), role: 'assistant', content: response.answer, created_at: new Date().toISOString() }]); await refreshConversations() } catch (reason) { setError(getErrorMessage(reason, 'Không thể kết nối trợ lý lúc này.')); setMessages(items => items.filter(item => item.id !== local.id)) } finally { setSending(false) } }
  return <div className="mx-auto grid max-w-6xl gap-5 lg:grid-cols-[240px_1fr]"><Card className="h-fit"><div className="flex items-center justify-between"><strong>Lịch sử</strong><button aria-label="Cuộc trò chuyện mới" onClick={() => { setConversationId(undefined); setMessages([]); setError('') }}>＋</button></div><div className="mt-3 space-y-1">{conversations.map(item => <div key={item.id} className={`flex items-center rounded-lg ${item.id === conversationId ? 'bg-indigo-50' : ''}`}><button className="min-w-0 flex-1 truncate px-2 py-2 text-left text-sm" onClick={() => void openConversation(item.id)}>{item.title}</button><button aria-label={`Xóa ${item.title}`} className="p-2 text-slate-400 hover:text-rose-600" onClick={() => void removeConversation(item.id)}><Trash2 size={14}/></button></div>)}</div></Card><div><div className="mb-6"><p className="flex items-center gap-2 text-sm font-medium text-indigo-600"><Sparkles size={16}/> Trợ lý cá nhân</p><h1 className="mt-1 text-3xl font-bold">Làm việc thông minh hơn</h1><p className="mt-2 text-slate-500">Hỏi đáp, hướng dẫn, lập kế hoạch và chia nhỏ công việc. AI không tự thay đổi dữ liệu.</p></div>{error && <p role="alert" className="mb-4 rounded-xl bg-rose-50 p-3 text-sm text-rose-700">{error}</p>}<Card className="flex min-h-[560px] flex-col"><div className="flex-1 space-y-4">{messages.length === 0 && <div className="grid place-items-center py-16 text-center text-slate-500"><Bot className="mb-3 text-indigo-500" size={42}/><p>Chọn gợi ý hoặc viết câu hỏi của bạn.</p><div className="mt-5 flex flex-wrap justify-center gap-2">{prompts.map(prompt => <button key={prompt} onClick={() => void send(prompt)} className="rounded-full border border-indigo-200 px-3 py-2 text-sm text-indigo-700 hover:bg-indigo-50">{prompt}</button>)}</div></div>}{messages.map(message => <div key={message.id} className={`flex ${message.role === 'user' ? 'justify-end' : 'justify-start'}`}><p className={`max-w-[85%] whitespace-pre-wrap rounded-2xl px-4 py-3 text-sm ${message.role === 'user' ? 'bg-indigo-600 text-white' : 'bg-slate-100'}`}>{message.content}</p></div>)}</div><div className="mt-5 flex gap-2 border-t border-slate-100 pt-4"><Input aria-label="Tin nhắn cho AI" value={input} onChange={event => setInput(event.target.value)} onKeyDown={event => { if (event.key === 'Enter' && !event.shiftKey) void send() }} placeholder="Ví dụ: Hướng dẫn tôi lập kế hoạch tuần…"/><Button aria-label="Gửi" onClick={() => void send()} disabled={sending}><Send size={17}/></Button></div></Card></div></div>
}
