import { useForm } from 'react-hook-form'
import { zodResolver } from '@hookform/resolvers/zod'
import { Link, useNavigate } from 'react-router-dom'
import { z } from 'zod'
import { useAuth } from '../hooks/useAuth'
import { Button, Input } from '../components/ui'
import { getErrorMessage } from '../api/client'
import { useState } from 'react'
const schema = z.object({ full_name: z.string().min(2, 'Tên tối thiểu 2 ký tự').max(120), email: z.email('Email không hợp lệ'), password: z.string().min(8, 'Mật khẩu tối thiểu 8 ký tự').regex(/[A-Z]/, 'Cần ít nhất một chữ hoa').regex(/[a-z]/, 'Cần ít nhất một chữ thường').regex(/\d/, 'Cần ít nhất một chữ số') })
type FormValues = z.infer<typeof schema>
export function RegisterPage() { const { register: signUp } = useAuth(); const navigate = useNavigate(); const [error, setError] = useState(''); const { register, handleSubmit, formState: { errors, isSubmitting } } = useForm<FormValues>({ resolver: zodResolver(schema) }); const submit = async (values: FormValues) => { try { await signUp(values); navigate('/app', { replace: true }) } catch (reason) { setError(getErrorMessage(reason, 'Không thể tạo tài khoản.')) } }; return <div><h1 className="text-3xl font-bold">Tạo tài khoản</h1><p className="mt-2 text-slate-500">Bắt đầu một ngày làm việc nhẹ nhàng hơn.</p><form onSubmit={handleSubmit(submit)} className="mt-8 space-y-5"><label className="block text-sm font-medium">Họ và tên<Input className="mt-1.5" {...register('full_name')} /></label>{errors.full_name && <p className="-mt-4 text-sm text-rose-600">{errors.full_name.message}</p>}<label className="block text-sm font-medium">Email<Input className="mt-1.5" type="email" autoComplete="email" {...register('email')} /></label>{errors.email && <p className="-mt-4 text-sm text-rose-600">{errors.email.message}</p>}<label className="block text-sm font-medium">Mật khẩu<Input className="mt-1.5" type="password" autoComplete="new-password" {...register('password')} /></label>{errors.password && <p className="-mt-4 text-sm text-rose-600">{errors.password.message}</p>}{error && <p role="alert" className="rounded-xl bg-rose-50 p-3 text-sm text-rose-700">{error}</p>}<Button className="w-full" disabled={isSubmitting}>{isSubmitting ? 'Đang tạo…' : 'Tạo tài khoản'}</Button></form><p className="mt-6 text-center text-sm text-slate-500">Đã có tài khoản? <Link className="font-semibold text-indigo-600" to="/login">Đăng nhập</Link></p></div> }
